const language = [
    { label: 'English', value: 'en'},
    { label: 'Chinese', value: 'zh'},
    { label: 'Arabic', value: 'ar'},
    { label: 'Spanish', value: 'es'},
    { label: 'Portuguese', value: 'pt'},
    { label: 'Russian', value: 'ru'},
    { label: 'Polish', value: 'pl'},
    { label: 'Persian', value: 'fa'},
    { label: 'Malay', value: 'ms'},
    { label: 'Dutch', value: 'nl'},
    { label: 'Thai', value: 'th'},
    { label: 'Turkish', value: 'tr'},
    { label: 'Ukrainian', value: 'uk'},
    { label: 'Vietnamese', value: 'vi'},
    { label: 'French', value: 'fr'},
    { label: 'German', value: 'de'},
    { label: 'Italian', value: 'it'},
    { label: 'Japanese', value: 'ja'},
    { label: 'Hindi', value: 'hi'},
    { label: 'Hungarian', value: 'hu'},
    { label: 'Indonesian', value: 'id'},
    { label: 'Korean', value: 'ko'},
    { label: 'Norwegian', value: 'nb'},
    { label: 'Catalan', value: 'ca'},
    { label: 'Croatian', value: 'hr'},
    { label: 'Czech', value: 'cs'},
    { label: 'Danish', value: 'da'},
    { label: 'Finnish', value: 'fi'},
    { label: 'Greek', value: 'el'},
    { label: 'Hebrew', value: 'he'},
    { label: 'Romanian', value: 'ro'},
    { label: 'Slovak', value: 'sk'}
]

export default language;

export const languageCodes = [ 'en', 'zh', 'ar', 'es', 'pt', 'ru', 'pl', 'fa', 'ms', 'nl', 'th', 'tr', 'uk', 'vi', 'fr', 'de', 'it', 'ja', 'hi', 'hu', 'id', 'ko', 'nb', 'ca', 'hr', 'cs', 'da', 'fi', 'el', 'he', 'ro', 'sk'];

export const languageMap = {
    'en': 'English',
    'zh': 'Chinese',
    'ar': 'Arabic',
    'es': 'Spanish',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'pl': 'Polish',
    'fa': 'Persian',
    'ms': 'Malay',
    'nl': 'Dutch',
    'th': 'Thai',
    'tr': 'Turkish',
    'uk': 'Ukrainian',
    'vi': 'Vietnamese',
    'fr': 'French',
    'de': 'German',
    'it': 'Italian',
    'ja': 'Japanese',
    'hi': 'Hindi',
    'hu': 'Hungarian',
    'id': 'Indonesian',
    'ko': 'Korean',
    'nb': 'Norwegian',
    'ca': 'Catalan',
    'hr': 'Croatian',
    'cs': 'Czech',
    'da': 'Danish',
    'fi': 'Finnish',
    'el': 'Greek',
    'he': 'Hebrew',
    'ro': 'Romanian',
    'sk': 'Slovak'
}