const languageMap = {
    "english": "en",
    "chinese": "zh",
    "arabic": "ar",
    "spanish": "es",
    "portuguese": "pt",
    "russian": "ru",
    "polish": "pl",
    "persian": "fa",
    "malay": "ms",
    "dutch": "nl",
    "thai": "th",
    "turkish": "tr",
    "ukrainian": "uk",
    "vietnamese": "vi",
    "french": "fr",
    "german": "de",
    "italian": "it",
    "japanese": "ja",
    "hindi": "hi",
    "hungarian": "hu",
    "indonesian": "id",
    "korean": "ko",
    "norwegian": "nb",
    "catalan": "ca",
    "croatian": "hr",
    "czech": "cs",
    "danish": "da",
    "finnish": "fi",
    "greek": "el",
    "hebrew": "he",
    "romanian": "ro",
    "slovak": "sk"
}

export default languageMap;