const languageMap = {
    "English": "en",
    "Chinese": "zh",
    "Arabic": "ar",
    "Spanish": "es",
    "Portuguese": "pt",
    "Russian": "ru",
    "Polish": "pl",
    "Persian": "fa",
    "Malay": "ms",
    "Dutch": "nl",
    "Thai": "th",
    "Turkish": "tr",
    "Ukrainian": "uk",
    "Vietnamese": "vi",
    "French": "fr",
    "German": "de",
    "Italian": "it",
    "Japanese": "ja",
    "Hindi": "hi",
    "Hungarian": "hu",
    "Indonesian": "id",
    "Korean": "ko",
    "Norwegian": "nb",
    "Catalan": "ca",
    "Croatian": "hr",
    "Czech": "cs",
    "Danish": "da",
    "Finnish": "fi",
    "Greek": "el",
    "Hebrew": "he",
    "Romanian": "ro",
    "Slovak": "sk"
}

export default languageMap;